### ISSUE TITLE
TypeError: originalValue.split is not a function

### ISSUE THREAD

**Issue by buschtoens** [rwjblue/ember-cli-template-lint#173]
Upgrading from 0.4.12 to 0.5.0 makes the terminal throw up a bunch of errors.

I copied the whole output [to a gist](https://gist.github.com/buschtoens/a90267ca944f1d9b956976c99cc03dca), but basically it's this:

```
undefined: originalValue.split is not a function (ddgweb/admin/customers/create/template): 
`TypeError: originalValue.split is not a function
    at manageMustacheViewInvocation (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/deprecations/lint-deprecated-inline-view-helper.js:42:25)
    at BasePlugin.MustacheStatement (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/deprecations/lint-deprecated-inline-view-helper.js:83:11)
    at invokeVisitorEnter (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:14:15)
    at enter (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:83:11)
    at visitNode (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:18:28)
    at visitArray (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
    at visitKey (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
    at visitNode (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
    at Object.traverse (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:110:3)
    at BasePlugin.transform (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:41:17)
    at Object.preprocess (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/parser.js:45:25)
    at compileSpec (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:39:35)
    at compile (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:88:46)
    at Linter.verify (/home/jan/workspace/web/node_modules/ember-template-lint/lib/index.js:86:7)
    at TemplateLinter.processString (/home/jan/workspace/web/node_modules/ember-cli-template-lint/broccoli-template-linter.js:91:28)
    at Promise.then.result.output (/home/jan/workspace/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /home/jan/workspace/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at tryCatch (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`
```

and

```
undefined: Cannot read property 'split' of undefined (ddgweb/auskunft/search/template): 
`TypeError: Cannot read property 'split' of undefined
    at manageMustacheViewInvocation (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/deprecations/lint-deprecated-inline-view-helper.js:42:24)
    at BasePlugin.MustacheStatement (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/deprecations/lint-deprecated-inline-view-helper.js:83:11)
    at invokeVisitorEnter (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:14:15)
    at enter (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:83:11)
    at visitNode (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:18:28)
    at visitArray (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
    at visitKey (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
    at visitNode (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
    at Object.traverse (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:110:3)
    at BasePlugin.transform (/home/jan/workspace/web/node_modules/ember-template-lint/lib/rules/base.js:41:17)
    at Object.preprocess (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-syntax/parser.js:45:25)
    at compileSpec (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:39:35)
    at compile (/home/jan/workspace/web/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:88:46)
    at Linter.verify (/home/jan/workspace/web/node_modules/ember-template-lint/lib/index.js:86:7)
    at TemplateLinter.processString (/home/jan/workspace/web/node_modules/ember-cli-template-lint/broccoli-template-linter.js:91:28)
    at Promise.then.result.output (/home/jan/workspace/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /home/jan/workspace/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at tryCatch (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/jan/workspace/web/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

For example, this `application.hbs` triggers the error:

```hbs
{{title "CrossCheck Web" prepend=true separator=" | "}}

{{#if session.isAuthenticated}}
  {{application-navigation}}
{{/if}}

{{! TODO: remove wrapper once routable components land }}
<div class="application-outlet">
  {{outlet}}
</div>
```

**Comment by rwjblue** [comment]
Whoops!  Looks like we are making the assumption that something is a string that isn't.  

@buschtoens - It would be quite helpful if you could submit a minimal failing template test case to the upstream https://github.com/rwjblue/ember-template-lint repo.  I _think_ all you should need to do is add another entry in the `good` template's list [like this one](https://github.com/rwjblue/ember-template-lint/blob/e8dcdf105d0f08e9a65a1f43ad904d669ee265aa/test/unit/rules/deprecations/lint-deprecated-inline-view-helper-test.js#L15-L17).  Once we know exactly what is causing the issue, I'll try to jump on the fix (or guide you if you are still up for helping with it after all that ;P ).

**Comment by buschtoens** [comment]
Will do :+1:

**Comment by dfalling** [comment]
I'm hitting this as well with i18n: 
```handlebars
{{input placeholder=(t "email") value=email}}
```

**Comment by duggiefresh** [comment]
@buschtoens @rwjblue Whoopies. My bad, I pushed up this PR https://github.com/rwjblue/ember-template-lint/pull/129

Thanks
