### ISSUE TITLE
this.ui.warn is not a function

### ISSUE THREAD

**Issue by KillaPL** [rwjblue/ember-cli-template-lint#261]
I am trying to update to new 0.7.0 version, and when I do that, and try to `ember test` or `ember serve`, I receive the error in title. Backtrace:

```
this.ui.warn is not a function
TypeError: this.ui.warn is not a function
```

This is relevant part of my package.json:

```
  "dependencies": {
    "cirilla": "1.0.5",
    "ember-api-requests": "0.3.1",
    "ember-inflector": "2.0.0",
    "marked": "0.3.6"
  },
  "devDependencies": {
    "broccoli-asset-rev": "2.5.0",
    "ember-ajax": "2.5.6",
    "ember-browserify": "1.1.13",
    "ember-cli": "2.13.0",
    "ember-cli-app-version": "2.0.0",
    "ember-cli-babel": "6.1.0",
    "ember-cli-code-coverage": "0.3.11",
    "ember-cli-dependency-checker": "1.3.0",
    "ember-cli-dependency-lint": "^1.0.2",
    "ember-cli-eslint": "3.1.0",
    "ember-cli-htmlbars": "1.3.0",
    "ember-cli-htmlbars-inline-precompile": "0.4.2",
    "ember-cli-inject-live-reload": "1.4.1",
    "ember-cli-local-storage-wrapper": "0.6.0",
    "ember-cli-mirage": "0.3.3",
    "ember-cli-moment-shim": "3.3.1",
    "ember-cli-node-assets": "0.1.6",
    "ember-cli-qunit": "4.0.0-beta.1",
    "ember-cli-release": "0.2.9",
    "ember-cli-sass": "6.1.1",
    "ember-cli-sass-lint": "1.0.3",
    "ember-cli-shims": "1.0.2",
    "ember-cli-sri": "2.1.0",
    "ember-cli-template-lint": "0.7.0",
    "ember-cli-test-loader": "2.1.0",
    "ember-cli-uglify": "1.2.0",
    "ember-cli-windows-addon": "1.3.1",
    "ember-composable-helpers": "2.0.0",
    "ember-cp-validations": "3.3.1",
    "ember-custom-actions": "1.2.2",
    "ember-data": "2.13.0",
    "ember-drag-drop": "0.4.3",
    "ember-export-application-global": "1.0.5",
    "ember-load-initializers": "1.0.0",
    "ember-moment": "7.3.1",
    "ember-pluralize": "0.2.0",
    "ember-power-calendar": "0.5.0",
    "ember-radio-button": "1.1.1",
    "ember-resolver": "4.1.0",
    "ember-source": "2.11.0",
    "ember-truth-helpers": "1.3.0",
    "loader.js": "4.4.0"
  },
```

In that `cirilla` is inner company styles lib. I also tried updating to `ember-source` 2.13.0 and `ember-cli` 2.13.2 with no luck.

I am quite unsure where this function `this.ui.warn` is supposed to be coming from, please let me know how can I further help with solving this issue. Should I provide more data from package.json?

**Comment by KillaPL** [comment]
This problem was actually solved by moving to `ember-cli-qunit` in version `4.0.0`. Should I close this issue? Posting this, as this information might be useful to somebody else.

**Comment by rwjblue** [comment]
What was the full stacktrace?

**Comment by KillaPL** [comment]
```
TypeError: this.ui.warn is not a function
  at Class.included (/app-directory/node_modules/ember-cli-template-lint/index.js:25:17)
  at Class.superWrapper [as included] (/app-directory/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
  at EmberApp.<anonymous> (/app-directory/node_modules/ember-cli/lib/broccoli/ember-app.js:517:17)
  at Array.filter (native)
  at EmberApp._notifyAddonIncluded (/app-directory/node_modules/ember-cli/lib/broccoli/ember-app.js:512:47)
  at new EmberApp (/app-directory/node_modules/ember-cli/lib/broccoli/ember-app.js:142:10)
  at module.exports (/app-directory/ember-cli-build.js:44:15)
  at Builder.setupBroccoliBuilder (/app-directory/node_modules/ember-cli/lib/models/builder.js:56:19)
  at new Builder (/app-directory/node_modules/ember-cli/lib/models/builder.js:30:10)
  at BuildTask.run (/app-directory/node_modules/ember-cli/lib/tasks/build.js:15:19)
```

I replaced actual app directory with `/app-directory`. This happens on `ember test`.

**Comment by rwjblue** [comment]
So it was an issue fixed between ember-cli-qunit 4.0.0-beta.1 and 4.0.0?

**Comment by KillaPL** [comment]
Exactly, moving to 4.0.0 makes the tests pass in flying colors.

**Comment by rwjblue** [comment]
Hmm. Ok, lets close his then. Though I'm happy to reopen if others run into it...
