### ISSUE TITLE
TypeError: this.ui.warn is not a function

### ISSUE THREAD

**Issue by Turbo87** [rwjblue/ember-cli-template-lint#284]
```
$ ember exam --split 3 --parallel
TypeError: this.ui.warn is not a function
    at Class.included (/Users/tbieniek/Code/foo/node_modules/ember-cli-template-lint/index.js:25:17)
    at Class.superWrapper [as included] (/Users/tbieniek/Code/foo/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberApp.<anonymous> (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/broccoli/ember-app.js:529:17)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/broccoli/ember-app.js:526:47)
    at new EmberApp (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/broccoli/ember-app.js:146:10)
    at module.exports (/Users/tbieniek/Code/foo/ember-cli-build.js:13:13)
    at Builder.setupBroccoliBuilder (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/Users/tbieniek/Code/foo/node_modules/ember-cli/lib/tasks/build.js:15:19)
```

This seems to happen when the test framework can not be identified for some reason 🤔

**Comment by Turbo87** [comment]
the correct API seems to be `this.ui.writeWarnLine()` according to https://github.com/ember-cli/console-ui#usage

**Comment by rwjblue** [comment]
Ugh. Thanks for reporting. Will fix ASAP.
